spring:
  application:
    name: student-management-system-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: student_management_system
    password: password
  flyway:
    enabled: true
    locations: classpath:/db/migration
  data:
    redis:
      host: localhost
      port: 6379

cache:
  type: redis

server:
  port: 8000

jwt:
  secret: "P2K5063E3Y6tpPCBMdyZxQ1ijvrnOnmNPxwc52efZIxFD2AvKbe61sHMOaJO2efZIxFD2AvKbe61sHMOaJO"
  expiration: 300000
  refreshExpiration: 330000