-- Create Users Table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    role VARCHAR2(10) CHECK (role IN ('ADMIN', 'STUDENT')) NOT NULL
);

-- Create Courses Table
CREATE TABLE courses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR2(10) UNIQUE NOT NULL,
    course_name VARCHAR2(100) NOT NULL,
    description CLOB,
    credits NUMBER NOT NULL,
    schedule CLOB
);

-- Create Registrations Table
CREATE TABLE registrations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR2(10) CHECK (status IN ('REGISTERED', 'CANCELLED')) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (course_id) REFERENCES courses(id)
);

-- Create Indexes for Foreign Keys in Registrations Table
CREATE INDEX idx_registrations_user_id ON registrations(user_id);
CREATE INDEX idx_registrations_course_id ON registrations(course_id);

-- Insert Test Data into Users Table
INSERT INTO users (username, password_hash, email, first_name, last_name, role)
VALUES ('student1', 'password1', 'student1@example.com', 'Medhat', 'Hamza', 'STUDENT');
INSERT INTO users (username, password_hash, email, first_name, last_name, role)
VALUES ('student2', 'password2', 'student2@example.com', 'Abdelrahman', 'Hamza', 'STUDENT');
INSERT INTO users (username, password_hash, email, first_name, last_name, role)
VALUES ('admin', 'admin', 'admin1@example.com', 'Mahmoud', 'Hamza', 'ADMIN');

-- Insert Test Data into Courses Table
INSERT INTO courses (course_code, course_name, description, credits, schedule)
VALUES ('CS101', 'Introduction to Computer Science', 'Basic concepts of computer science', 3, '{"Monday": "10:00-12:00", "Wednesday": "10:00-12:00"}');
INSERT INTO courses (course_code, course_name, description, credits, schedule)
VALUES ('MATH201', 'Calculus I', 'Introduction to calculus', 4, '{"Tuesday": "09:00-11:00", "Thursday": "09:00-11:00"}');

-- Insert Test Data into Registrations Table
INSERT INTO registrations (user_id, course_id, registration_date, status)
VALUES (1, 1, SYSTIMESTAMP, 'REGISTERED');
INSERT INTO registrations (user_id, course_id, registration_date, status)
VALUES (2, 1, SYSTIMESTAMP, 'REGISTERED');
INSERT INTO registrations (user_id, course_id, registration_date, status)
VALUES (1, 2, SYSTIMESTAMP, 'REGISTERED');